In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Classification_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# K-Nearest Neighbors Classifier
from sklearn.neighbors import KNeighborsClassifier
knnc = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knnc.fit(X_train, y_train)
print(knnc)

# Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(random_state = 0)
lrc.fit(X_train, y_train)
print(lrc)

# Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
nbc = GaussianNB()
nbc.fit(X_train, y_train)
print(nbc)

# Support Vector Classifier
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf', random_state = 0)
svc.fit(X_train, y_train)
print(svc)

# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfc.fit(X_train, y_train)
print(rfc)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
GaussianNB(priors=None, var_smoothing=1e-09)
SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, 

In [8]:
knnc_pred = knnc.predict(X_test)
lrc_pred = lrc.predict(X_test)
nbc_pred = nbc.predict(X_test)
svc_pred = svc.predict(X_test)
rfc_pred = rfc.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

knnc_cm = confusion_matrix(y_test, knnc_pred)
lrc_cm = confusion_matrix(y_test, lrc_pred)
nbc_cm = confusion_matrix(y_test, nbc_pred)
svc_cm = confusion_matrix(y_test, svc_pred)
rfc_cm = confusion_matrix(y_test, rfc_pred)

knnc_acc = accuracy_score(y_test, knnc_pred)
lrc_acc = accuracy_score(y_test, lrc_pred)
nbc_acc = accuracy_score(y_test, nbc_pred)
svc_acc = accuracy_score(y_test, svc_pred)
rfc_acc = accuracy_score(y_test, rfc_pred)
print("Confusion Matrices for the classifiers are:")
print("K-Nearest Neighbors Classifier\n",knnc_cm,"\nLogistic Regression Classifier\n",lrc_cm,"\nNaive Bayes Classifier\n",nbc_cm,\
"\nSupport Vector Classifier\n",svc_cm,"\nRandom Forest Classifier\n",rfc_cm)
print("\nAccuracies for the classifiers are:")
print("K-Nearest Neighbors Classifier\t",knnc_acc,"\nLogistic Regression Classifier\t",lrc_acc,"\nNaive Bayes Classifier\t\t",nbc_acc,\
"\nSupport Vector Classifier\t",svc_acc,"\nRandom Forest Classifier\t",rfc_acc)

Confusion Matrices for the classifiers are:
K-Nearest Neighbors Classifier
 [[103   4]
 [  5  59]] 
Logistic Regression Classifier
 [[103   4]
 [  5  59]] 
Naive Bayes Classifier
 [[99  8]
 [ 2 62]] 
Support Vector Classifier
 [[102   5]
 [  3  61]] 
Random Forest Classifier
 [[102   5]
 [  6  58]]

Accuracies for the classifiers are:
K-Nearest Neighbors Classifier	 0.9473684210526315 
Logistic Regression Classifier	 0.9473684210526315 
Naive Bayes Classifier		 0.9415204678362573 
Support Vector Classifier	 0.9532163742690059 
Random Forest Classifier	 0.935672514619883
